In [1]:
# Importing dependencies

from learntools.core import binder
import numpy as np

binder.bind(globals())

from learntools_ex import *

print("Setup Complete")

Setup Complete


## **Questions**

### **IMPORTANT**: You **don't** have to delete any `q{n}.check()` or `q{n}.hint()` or `q{n}_sol = question_{n}()`. Please make sure that the function name and function signature match the question and the example given. Additionally, all functions should be runnable or your solution will not be evaluated.

## **Q1:** Create a one-dimensional NumPy array of the numbers from 5 to 905, counting by 10, exclusive 905?

In [ ]:
import numpy as np
arr = np.arange(5, 905, 10)
print(arr)

## **Q2**: Create the same NumPy array using a Python range and a list? (Hint: create a list)

In [2]:
import numpy as np


py_range = range(5, 905, 10)


arr = np.array(list(py_range))

print(arr)

[  5  15  25  35  45  55  65  75  85  95 105 115 125 135 145 155 165 175
 185 195 205 215 225 235 245 255 265 275 285 295 305 315 325 335 345 355
 365 375 385 395 405 415 425 435 445 455 465 475 485 495 505 515 525 535
 545 555 565 575 585 595 605 615 625 635 645 655 665 675 685 695 705 715
 725 735 745 755 765 775 785 795 805 815 825 835 845 855 865 875 885 895]


## **Q3**: How might you create a NumPy array of the capital letters, A-Z? (Hint: Ever heard of string.ascii_uppercase?)

In [ ]:
import numpy as np
import string

letters_array = np.array(list(string.ascii_uppercase))

print(letters_array)

## **Q4**: Create a ten-element NumPy array object of all zeros and a six-element NumPy array object of all ones.

In [ ]:
import numpy as np


zeros_array = np.zeros(10)  


ones_array = np.ones(6)    

print("Zeros array:", zeros_array)
print("Ones array:", ones_array)

## **Q5**: Given an 2-D array, print the third column.

In [ ]:
import numpy as np


arr = np.array([[11, 22, 33],
                [44, 55, 66],
                [77, 88, 99]])


third_column = arr[:, 2]


## **Q6**: Create an array of the shape (3, 4), filled with 64-bit integer zeros.

In [ ]:
import numpy as np


zeros_array = np.zeros((3, 4), dtype=np.int64)

print(zeros_array)

## **Q7**: Split an array into 3 equal-sized sub-arrays.

In [ ]:
import numpy as np

arr = np.arange(7, 34, 1).reshape(9, 3)
print("Original Array:\n", arr)


## **Q8**: Return the last 2 elements by each of the first two rows of the (3,4) array. 

In [ ]:
import numpy as np

arr = np.arange(1, 13, 1).reshape(3, 4)
print("Original Array:\n", arr)

## **Q9**: Return how many elements are greater than 5 in an array.

In [ ]:
import numpy as np

arr = np.arange(1, 13, 1).reshape(3, 4)
count = np.sum(arr > 5)  # Sums `True` values (1) where condition is met

print("Number of elements > 5:", count)

## **Q10**: Delete the second column from an array and insert the following new column in the same place.

In [ ]:
input = np.array([[34, 72, 33], [82, 22, 32], [59, 84, 10]])
insert_data = np.array([[37, 37, 37]])


arr[:, 1] = insert_data.flatten()  
print("Direct replacement:\n", arr)

Direct replacement:
 [[ 1 37  3  4]
 [ 5 37  7  8]
 [ 9 37 11 12]]


## **Q11**: Compute the Euclidean distance between each pair of consecutive points in a given 2D NumPy array and append the result as a new column. Pad with 0 for missing data.

Euclidian distance between two points $(x_1, y_1)$ and $(x_2, y_2)$ is $\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$.  

In [ ]:
input = np.array([[1, 2], [4, 6], [7, 8], [10, 10]])


diff = np.diff(points, axis=0)  # Differences between consecutive points
distances = np.sqrt(np.sum(diff**2, axis=1))  # Euclidean distances



## **Q12**: Remove consecutive duplicates from a NumPy array.

In [ ]:
input = np.array([[1, 1], [2, 1], [3, 3], [3, 3], [2, 1], [1, 1]])


def question_12(input):
    raise NotImplementedError


q12_sol = question_12(input)
q12.check()

## **Q13**: Given a 2D NumPy array representing strokes, normalize all rows by subtracting the mean of each column and dividing by the standard deviation, but avoid division by zero.
$X_{\text{normalized}} = \frac{X - \mu}{\sigma}$

In [ ]:



import numpy as np

def safe_normalize(X):
    
    mu = np.mean(X, axis=0)
    sigma = np.std(X, axis=0)
    
    
    sigma[sigma == 0] = 1
    
    
    X_normalized = (X - mu) / sigma
    return X_normalized


X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
X_normalized = safe_normalize(X)
print("Normalized array:\n", X_normalized)

## **Q14**: Delete the second column from an array and insert a new column at the same position where each value is the sum of its corresponding row.

In [ ]:
import numpy as np


arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])


arr_deleted = np.delete(arr, 1, axis=1)


row_sums = arr_deleted.sum(axis=1, keepdims=True)


arr_final = np.insert(arr_deleted, 1, row_sums, axis=1)

print("Final Array:\n", arr_final)

## **Q15**: Extract Unique Characters from a NumPy Array of Strings
Given a 1D NumPy array of strings, extract all unique characters present in the array and sort by their ASCII values.

In [ ]:
import numpy as np

input_array = np.array(["hello", "world", "numpy", "rocks"])


combined_string = ''.join(input_array)

unique_chars = sorted(set(combined_string))

print("Unique characters:", unique_chars)

## **Q16**: Generate a dictionary that maps each unique character to a unique index starting with 0, sorted by ascending ASCII value.

In [ ]:
import numpy as np

input_array = np.array(["a", "b", "c", "d", "a", "c", "e"])


unique_chars = sorted(np.unique(input_array))


char_to_index = {char: idx for idx, char in enumerate(unique_chars)}

print("Character to Index Mapping:", char_to_index)

## **Q17**: Convert a List of 2D traces into a Single NumPy Array
Given a list of 2D traces (each being a NumPy array of shape `(N, 2)`), stack them into a single NumPy array.

In [ ]:
import numpy as np

input_list = [np.array([[1, 2], [3, 4]]), 
              np.array([[5, 6], [7, 8], [9, 10]])]


combined_array = np.vstack(input_list)

print("Combined Array:\n", combined_array)

## **Q18**: Convert a List of Text Labels into a NumPy Array of Integer Encodings
Given a vocabulary dictionary and a string of space-separated labels, convert the text into a NumPy array of indices.

In [ ]:
import numpy as np


label_to_index = {
    "hello": 0,
    "numpy": 1,
    "rocks": 2,
    "world": 3,
    "python": 4,
    "data": 5,
    "science": 6,
}


labels = ["hello", "world", "numpy", "rocks", "data", "python"]


encoded_array = np.array([label_to_index[label] for label in labels])

print("Encoded Array:", encoded_array)

## **Q19**: Extract Non-Zero Differences from an Array
Given a NumPy array of first-order differences, extract only non-zero differences using masking.

In [ ]:
import numpy as np

arr = np.array([[3, 4], [0, 0], [-2, 1]])


diff = np.diff(arr, axis=0)


non_zero_diff = diff[~np.all(diff == 0, axis=1)]

print("Non-zero differences:\n", non_zero_diff)

## **Q20**: Time Series Data Transformation and Feature Engineering

### *Problem Statement:*  
You are given a time series dataset representing sensor readings from multiple devices. Each row consists of sensor values at a specific timestamp. Your task is to preprocess and extract meaningful features from the dataset by performing the following transformations:

### *Steps to Follow:*
1. Normalize Each Sensor Reading  
- Subtract the mean and divide by the standard deviation for each column.  
- Avoid division by zero by replacing std=0 with 1.  
2. Detect and Mask Anomalous Values
- If a sensor reading is more than 2.5 standard deviations away from the mean, replace it with NaN.
3. Interpolate Missing Values (NaN Handling)
- Fill NaN values with the average of the nearest non-NaN neighbors.
4. Extract First-Order Differences
- Compute the difference between consecutive time steps for each sensor.
- Padding with 0 for missing data
5. Add Binary Columns for Missing Data
- Stack All Features into a Final Matrix
Create new columns `missing_flag` that is `1` where original data was `NaN`, otherwise `0`.
6. Stack All Features into a Final Matrix
- The final dataset should have normalized values, first-order differences, and the missing flag.

Expected shape (5, 9)

In [1]:
import numpy as np
from numpy import nan

def preprocess_time_series(input):
    
    mean = np.mean(input, axis=0)
    std = np.std(input, axis=0)
    std[std == 0] = 1
    normalized = (input - mean) / std

    
    anomaly_mask = np.abs(normalized) > 2.5
    normalized_with_nan = normalized.copy()
    normalized_with_nan[anomaly_mask] = nan

   
    def interpolate_nan(arr):
        for col in range(arr.shape[1]):
            nan_indices = np.isnan(arr[:, col])
            if not np.any(nan_indices):
                continue
            valid_indices = np.where(~nan_indices)[0]
            for i in np.where(nan_indices)[0]:
                left = valid_indices[valid_indices < i]
                right = valid_indices[valid_indices > i]
                if len(left) == 0 and len(right) == 0:
                    continue
                elif len(left) == 0:
                    arr[i, col] = arr[right[0], col]
                elif len(right) == 0:
                    arr[i, col] = arr[left[-1], col]
                else:
                    arr[i, col] = (arr[left[-1], col] + arr[right[0], col]) / 2
        return arr

    interpolated = interpolate_nan(normalized_with_nan.copy())


    first_order_diff = np.zeros_like(interpolated)
    first_order_diff[1:] = np.diff(interpolated, axis=0)

   
    missing_flag = np.zeros_like(normalized_with_nan)
    missing_flag[np.isnan(normalized_with_nan)] = 1

    
    final_matrix = np.hstack([interpolated, first_order_diff, missing_flag])

    return final_matrix


input = np.array(
    [
        [1.0, 10.0, 100.0],
        [2.0, 20.0, 200.0],
        [3.0, 30.0, 10000.0],  # Outlier in third column
        [4.0, 40.0, 400.0],
        [5.0, 50.0, 500.0],
    ]
)

output = preprocess_time_series(input)
print("Final output shape:", output.shape)
print("Final output:")
print(output)

Final output shape: (5, 9)
Final output:
[[-1.41421356 -1.41421356 -0.55118039  0.          0.          0.
   0.          0.          0.        ]
 [-0.70710678 -0.70710678 -0.52542429  0.70710678  0.70710678  0.02575609
   0.          0.          0.        ]
 [ 0.          0.          1.99867281  0.70710678  0.70710678  2.5240971
   0.          0.          0.        ]
 [ 0.70710678  0.70710678 -0.47391211  0.70710678  0.70710678 -2.47258492
   0.          0.          0.        ]
 [ 1.41421356  1.41421356 -0.44815602  0.70710678  0.70710678  0.02575609
   0.          0.          0.        ]]
